anomic30/Storz

- client/src/pages/landing/Landing.jsx
Fix hover effect on lading page, without affecting other expected component behaviour in other pages of the application
Fixes #20
> bug(hover): Fix hover in landing page

- client/src/components/file-desc/Desc.jsx
- client/src/pages/myFiles/MyFiles.jsx
- client/src/utils/formatDates.js
Added a function that returns the file upload date in a more human-readable format.
> feat: date formatter

- client/package-lock.json
- client/package.json
- client/src/pages/myFiles/MyFiles.css
- client/src/pages/myFiles/MyFiles.jsx
`1.` Fixes the squished text and minimalizes the text on screen on mobile devices.
`2.` Fixed accessibility of the page's images.
`3.` Adds `cross-env` for any and all env-vars on windows. [E.g.: The `build` command for client.]
Fixes #30 (issue)
* Styling
* OS support
> Fix for responsiveness and basic accessibility of file list page, while adding cross-env.

- client/README.md
Added Step 4 and 5 to clarify. Deleted the template sentence of create react app too.
Please label this as hacktoberfest-accepted if you merge this. thanks a lot <3
Fixes # (issue)
> Updated Readme using as a beginner

- server/index.js
- server/middlewares/rateLimiter.js
- server/package-lock.json
- server/package.json
I have added a rate limiter (express rate limiter) to the server to limit requests to avoid attacks like slowloris.
Fixes #43 
- [] I have made corresponding changes to the documentation
> Added rate limiter to server

- client/src/pages/signin/Signin.css
- client/src/pages/signin/Signin.jsx
I change the way how sign-in and log-in works by changing them to a form. It responds to actions like manually clicking the submit button or pressing enter.
Fixes issue #36
> Fix sign-in and log-in for better UX

- STYLEGUIDE.md
Added style guide for this project
> Added Styleguide

- server/routes/download.js
Code in download.ts was duplicated. I removed duplication by creating a function. Making it easier to maintain and read.
Improving existing code
> refactor(download): create function with duplicated code

- client/src/components/file-desc/Desc.css
- client/src/pages/myFiles/MyFiles.css
The application now will have an enhanced user experience while navigating through Files Section when the file name is too large
Mobile:
Desktop:
Even when the file name is not that large, for mobile devices the Ellipsis truncation is done for better visualization:
Fixes #56
> Enhance file section when file name is too big

- client/src/pages/landing/Landing.css
- client/src/pages/landing/Landing.jsx
Added scroll back to the top button on the landing page in order to improve the user experience.
> added scroll to top to improve UX

- client/src/pages/landing/Landing.css
Added responsiveness to the scroll to top button for both tablet and mobile view
> added responsiveness to the scroll to top button for both tablet and mobile

- CONTRIBUTING.md
⚠️ We are not assigning issues to anyone. Only the first PR related to the issue will be considered.
> updated guidelines for PR

- client/src/pages/myFiles/MyFiles.css
> fix: removed outlines appearing while clicking on pagination buttons

- CONTRIBUTING.md
- README.md
- client/src/pages/myFiles/MyFiles.css
Updated guidelines for node and npm versions.
> docs: updated guidelines for node and npm version

- client/src/pages/myFiles/MyFiles.jsx
- server/package-lock.json
The pagination issue in the "Files" section has been fixed.
> pagination issue fixed

- client/src/pages/myFiles/MyFiles.css
- client/src/pages/myFiles/MyFiles.jsx
> enhanced: left and right arrow for pagination

- client/src/components/modal/Modal.css
- client/src/components/modal/Modal.jsx
- client/src/pages/home/Home.css
- client/src/pages/home/Home.jsx
- server/routes/upload.js
If an existing file is uploaded again, a confirmation modal will pop up saying _"A file with name x already exists. Do you want to override it?_. If Yes, then the existing file will be overridden, and on No, the duplicate file will be skipped and the rest of the files will be uploaded. 
This will work even when trying to upload multiple duplicate files along with new files.
Fixes #104
Screenshot:
> Fix: Issue-104 Files with same name

- client/src/index.css
- client/src/pages/landing/Landing.css
> fix: breaking CSS in file desc component

- client/src/components/globe/Globe.jsx
This PR enhances the view and control of the landing page globe.
1. Enables auto rotation
2. Disables zooming
3. Uses better initial camera point of view (which also slightly increases the globe size on the webpage)
4. Limits vertical rotation on the globe to focus on the populated areas
> feat: improve view and control of landing page globe

- client/src/pages/home/Home.jsx
- server/routes/user.js
Fixed file not uploading issue in the home page.
Fixes # (issue)
> fix: file not uploading

- client/src/components/globe/Globe.jsx
- client/src/pages/landing/Landing.css
- client/src/pages/landing/Landing.jsx
Make the globe resize and hidden when not enough screen size.
> feat: make landing page 3D globe responsive

- client/src/components/modal/Modal.css
- client/src/pages/home/Home.css
> enhaced : modal for duplicate files

- client/src/pages/home/Home.css
> enhanced : upload button margin and cursor pointer to cross icon

- client/src/components/file-desc/Desc.jsx
> removed tooltip arrows

- client/src/components/globe/Globe.jsx
- client/src/pages/landing/Landing.jsx
Removes globe from DOM on small screen size instead of relying on CSS.
Additionally, slightly tuned the globe to make it look better.
> fix: landing page 3D globe enhancements
